version: "3.7"
services:
  postgres:
    image: postgres:11.6
    container_name: calorie-tracker-postgres
    ports:
      - 9000:5432
    environment:
      - POSTGRES_USER=calorie-tracker-user
      - POSTGRES_DB=calorie-tracker
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:3.2.5-alpine
    container_name: calorie-tracker-redis
    ports:
      - 9001:6379

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.0'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"