metadata:
  appName: "calorie-tracker"
  version: "v0.0.1"

http:
  address: localhost:8080

db:
  user: calorie-tracker-user
  pass: ""
  host: localhost
  database: calorie-tracker
  port: 9000
  poolSize: 20
  maxRetries: 3
  connectionTimeout: 1